//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class II_Stemming
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> docid { get; set; }
        public Nullable<int> frequency { get; set; }
        public string positions { get; set; }
    }
}
