//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRTest_Entities : DbContext
    {
        public IRTest_Entities()
            : base("name=IRTest_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bigram> Bigrams { get; set; }
        public DbSet<EnglishPage> EnglishPages { get; set; }
        public DbSet<II_Stemming> II_Stemming { get; set; }
        public DbSet<II_Stopwords> II_Stopwords { get; set; }
        public DbSet<SoundCode> SoundCodes { get; set; }
    }
}
